/*
 * Registers.h
 *
 *  Created on: Apr 28, 2025
 *      Author: manue
 */

#ifndef MODBUSMANAGER_REGISTERS_H_
#define MODBUSMANAGER_REGISTERS_H_

#ifdef __cplusplus
extern "C" {
#endif



//------------------------------------------------------------------------------
// Holding Registers
//

// Measurement Data
#define MODBUSMANAGER_MEASUREMENTDATA_TIMESTAMP					0x0000
#define MODBUSMANAGER_MEASUREMENTDATA_VDDA						0x0002
#define MODBUSMANAGER_MEASUREMENTDATA_VOLTAGE					0x0004
#define MODBUSMANAGER_MEASUREMENTDATA_CURRENT					0x0006
#define MODBUSMANAGER_MEASUREMENTDATA_POWER						0x0008
#define MODBUSMANAGER_MEASUREMENTDATA_RESISTANCE				0x000A
#define MODBUSMANAGER_MEASUREMENTDATA_TEMPFET					0x000C
#define MODBUSMANAGER_MEASUREMENTDATA_TEMPMCU					0x000E
#define MODBUSMANAGER_MEASUREMENTDATA_CHARGECOUNT				0x0010
#define MODBUSMANAGER_MEASUREMENTDATA_ENERGYCOUNT				0x0014
#define MODBUSMANAGER_MEASUREMENTDATA_DOUBLEBUFFER_TRIGGER		MODBUSMANAGER_MEASUREMENTDATA_TIMESTAMP

// Load Control
#define MODBUSMANAGER_LOADCONTROL_SETVOLTAGE					0x0000
#define MODBUSMANAGER_LOADCONTROL_SETCURRENT					0x0002
#define MODBUSMANAGER_LOADCONTROL_SETPOWER						0x0004
#define MODBUSMANAGER_LOADCONTROL_SETRESISTANCE					0x0006
#define MODBUSMANAGER_LOADCONTROL_VOLTAGELIMIT					0x0100
#define MODBUSMANAGER_LOADCONTROL_CURRENTLIMIT					0x0102
#define MODBUSMANAGER_LOADCONTROL_POWERLIMIT					0x0104
#define MODBUSMANAGER_LOADCONTROL_TEMPERATURELIMIT				0x0106
#define MODBUSMANAGER_LOADCONTROL_CONTROLREGISTER				0x0F00
#define MODBUSMANAGER_LOADCONTROL_STATUSREGISTER				0x0F01
#define MODBUSMANAGER_LOADCONTROL_DOUBLEBUFFER_TRIGGER			MODBUSMANAGER_LOADCONTROL_SETVOLTAGE

// Calibration
#define MODBUSMANAGER_CALIBRATION_VOLTAGECAL_FACTOR				0x1000
#define MODBUSMANAGER_CALIBRATION_VOLTAGECAL_OFFSET				0x1002
#define MODBUSMANAGER_CALIBRATION_CURRENTCAL_FACTOR				0x1004
#define MODBUSMANAGER_CALIBRATION_CURRENTCAL_OFFSET				0x1006
#define MODBUSMANAGER_CALIBRATION_CONTROLREGISTER				0x1F00
#define MODBUSMANAGER_CALIBRATION_DOUBLEBUFFER_TRIGGER			MODBUSMANAGER_CALIBRATION_VOLTAGECAL_FACTOR

// Auto-Zero
#define MODBUSMANAGER_AUTOZERO_VOLTAGE_OFFSET					0x2000
#define MODBUSMANAGER_AUTOZERO_CURRENT_OFFSET					0x2002
#define MODBUSMANAGER_AUTOZERO_VOLTAGE_LIMIT					0x2100
#define MODBUSMANAGER_AUTOZERO_CURRENT_LIMIT					0x2102
#define MODBUSMANAGER_AUTOZERO_CONTROLREGISTER					0x2F00
#define MODBUSMANAGER_AUTOZERO_DOUBLEBUFFER_TRIGGER				MODBUSMANAGER_AUTOZERO_VOLTAGE_OFFSET



#ifdef __cplusplus
}
#endif

#endif /* MODBUSMANAGER_REGISTERS_H_ */
